// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcHJTeTlYCOY6yWtR5pR63_Hrj0ZM1hNs',
    appId: '1:459685903213:web:10ca4d1077b80d62f3d492',
    messagingSenderId: '459685903213',
    projectId: 'multisalon-b6b70',
    authDomain: 'multisalon-b6b70.firebaseapp.com',
    storageBucket: 'multisalon-b6b70.appspot.com',
    measurementId: 'G-DL2X3CL4LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavf5fkRFUkI34Uyc3d8pTQmgyYSiM7y8',
    appId: '1:459685903213:android:a6ef77009c0455d9c7b864',
    messagingSenderId: '459685903213',
    projectId: 'multisalon-b6b70',
    storageBucket: 'multisalon-b6b70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiVgtMjBjVOD-SL55fKqgAbKGCPueDw2M',
    appId: '1:459685903213:ios:2065d2a0c20b3f79c7b864',
    messagingSenderId: '459685903213',
    projectId: 'multisalon-b6b70',
    storageBucket: 'multisalon-b6b70.appspot.com',
    iosClientId: '459685903213-sslblmdd2adkjrnuallnbfonpd087ina.apps.googleusercontent.com',
    iosBundleId: 'com.multisalon.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiVgtMjBjVOD-SL55fKqgAbKGCPueDw2M',
    appId: '1:459685903213:ios:2065d2a0c20b3f79c7b864',
    messagingSenderId: '459685903213',
    projectId: 'multisalon-b6b70',
    storageBucket: 'multisalon-b6b70.appspot.com',
    iosClientId: '459685903213-sslblmdd2adkjrnuallnbfonpd087ina.apps.googleusercontent.com',
    iosBundleId: 'com.multisalon.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcHJTeTlYCOY6yWtR5pR63_Hrj0ZM1hNs',
    appId: '1:459685903213:web:10ca4d1077b80d62f3d492',
    messagingSenderId: '459685903213',
    projectId: 'multisalon-b6b70',
    authDomain: 'multisalon-b6b70.firebaseapp.com',
    storageBucket: 'multisalon-b6b70.appspot.com',
    measurementId: 'G-DL2X3CL4LJ',
  );
}
